openapi: 3.0.0
info:
  version: 0.0.11
  title: Kartotherian
  description: Renders map tiles
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: MediaWiki maps development
    url: http://mediawiki.org/wiki/Maps
  license:
    name: Apache2 license
    url: http://www.apache.org/licenses/LICENSE-2.0

paths:
  # Tiles handler
  /{src}/{z}/{x}/{y}.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders an image tile for the given source, zoom, and coordinates.
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
            application/x-protobuf:
              schema:
                type: string
                format: binary
  # Tiles handler with scaling
  /{src}/{z}/{x}/{y}@{scale}x.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders an image tile for the given source, zoom, and coords, with scaling.
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
  # Source info
  /{src}/info.json:
    get:
      tags:
        - tileinfo
      responses:
        200:
          description: Gets information about the osm-intl source
          content:
            application/json:
              schema:
                type: string
                format: binary
  # Private source info
  /private-info/info.json:
    get:
      tags:
        - tileinfo
      responses:
        400:
          description: Returns error describing that given tile source is private
          content:
            application/json:
              schema:
                type: string
                format: binary
  # Maki icon markers (pushpins)
  # /v4/marker/{base}-{size}-{symbol}+{color}.png:
  /v4/marker/pin-m-fuel+ffffff.png:
    get:
      responses:
        200:
          description: Renders pushpin marker of a given color and size with an icon.
          content:
            image/png:
              schema:
                type: string
                format: binary
  # /v4/marker/{base}-{size}-{symbol}+{color}@{scale}x.png:
  /v4/marker/pin-m-fuel+ffffff@2x.png:
    get:
      tags:
        - marker
        - maki
      responses:
        200:
          description: Renders 2x scaled pushpin marker of a given color and size with an icon.
          content:
            image/png:
              schema:
                type: string
                format: binary
  # /v4/marker/{base}-{size}+{color}.png:
  /v4/marker/pin-m+ffffff.png:
    get:
      responses:
        200:
          description: Renders a pushpin marker of a given color and size without an icon
          content:
            image/png:
              schema:
                type: string
                format: binary
  # /v4/marker/{base}-{size}+{color}@{scale}x.png:
  /v4/marker/pin-m+ffffff@2x.png:
    get:
      responses:
        200:
          description: Renders 2x scaled pushpin marker of a given color and size without an icon.
          content:
            image/png:
              schema:
                type: string
                format: binary
  # Map snapshots
  /img/{src},{z},{lat},{lon},{w}x{h}.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders requested map region as an image (static map snapshot)
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
  /img/{src},{z},{lat},{lon},{w}x{h}@{scale}x.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders requested map region as a scaled image (static map snapshot)
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
  # geoline service
  /geoline?getgeojson=1&ids={ids}:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given line from Wikidata item ids
          content:
            application/vnd.geo+json:
              schema:
                type: string
                format: binary
  # geoshape service
  /geoshape?getgeojson=1&ids={ids}:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given shape from Wikidata item ids
          content:
            application/vnd.geo+json:
              schema:
                type: string
                format: binary
  # geopoint service
  /geopoint?getgeojson=1&ids={ids}:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given point from Wikidata item ids
          content:
            application/vnd.geo+json:
              schema:
                type: string
                format: binary
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      responses:
        200:
          description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      responses:
        200:
          description: The root service end-point
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      responses:
        200:
          description: Gets information about the service
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: true
  /_info/name:
    get:
      tags:
        - Service information
        - Service name
      responses:
        200:
          description: Gets the name of the service
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
  /_info/version:
    get:
      tags:
        - Service information
        - Service version
      responses:
        200:
          description: Gets the running version of the service
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
  /_info/home:
    get:
      tags:
        - Service information
        - Service homepage
      responses:
        200:
          description: Redirects to the home page
      x-monitor: false
