swagger: "2.0"
info:
  version: 0.0.11
  title: Kartotherian
  description: Renders map tiles
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: Yuri Astrakhan
    url: http://mediawiki.org/wiki/Maps
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0

paths:
  #  # Tiles handler
  #  # /{src}/{z}/{x}/{y}.{format}:
  /osm-intl/11/828/655.png:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
       200:
        description: Renders an image tile for the given source, zoom, and coordinates.
      produces:
        - image/png
        - application/json
        - application/x-protobuf
  # Tiles handler with scaling
  # /{src}/{z}/{x}/{y}@{scale}x.{format}:
  /osm-intl/11/828/655@1.5x.png:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
       200:
        description: Renders an image tile for the given source, zoom, and coordinates, with scaling.
      produces:
        - image/png
        - application/json
  # Source info
  # /{src}/info.json:
  /osm-intl/info.json:
    get:
      tags:
        - tileinfo
      produces:
        - application/json
      responses:
        200:
          description: Gets information about the osm-intl source
  # Private source info
  # /{src}/info.json:
  /private-info/info.json:
    get:
      tags:
        - tileinfo
      responses:
        400:
          description: Returns error describing that given tile source is private
      produces:
        - application/json; charset=utf-8
  # Maki icon markers (pushpins)
  # /v4/marker/{base}-{size}-{symbol}+{color}.png:
  /v4/marker/pin-m-fuel+ffffff.png:
    get:
      responses:
        200:
          description: Renders pushpin marker of a given color and size with an icon.
      produces:
        - image/png
  # /v4/marker/{base}-{size}-{symbol}+{color}@{scale}x.png:
  /v4/marker/pin-m-fuel+ffffff@2x.png:
    get:
      tags:
        - marker
        - maki
      responses:
        200:
          description: Renders 2x scaled pushpin marker of a given color and size with an icon.
      produces:
        - image/png
  # /v4/marker/{base}-{size}+{color}.png:
  /v4/marker/pin-m+ffffff.png:
    get:
      responses:
        200:
          description: Renders a pushpin marker of a given color and size without an icon
      produces:
        - image/png
  # /v4/marker/{base}-{size}+{color}@{scale}x.png:
  /v4/marker/pin-m+ffffff@2x.png:
    get:
      responses:
        200:
          description: Renders 2x scaled pushpin marker of a given color and size without an icon.
      produces:
        - image/png
  # Map snapshots
  # /img/{src},{z},{lat},{lon},{w}x{h}.{format}:
  /img/osm-intl,1,0.0,0.0,100x100.png:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders requested map region as an image (static map snapshot)
      produces:
        - image/png
  # /img/{src},{z},{lat},{lon},{w}x{h}@{scale}x.{format}:
  /img/osm-intl,1,0.0,0.0,100x100@2x.png:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders requested map region as a scaled image (static map snapshot)
      produces:
        - image/png
  # geoline service
  # /geoline?getgeojson=1&ids={ids}:
  /geoline?getgeojson=1&ids=Q649:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given line
      produces:
        - application/vnd.geo+json
  # geoshape service
  # /geoshape?getgeojson=1&ids={ids}:
  /geoshape?getgeojson=1&ids=Q6414:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given shape
      produces:
        - application/vnd.geo+json
  # geopoint service
  # /geopoint?getgeojson=1&ids={ids}:
  /geopoint?getgeojson=1&ids=Q151356:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Retrievs the location of a Wikidata item and returns a json representation of point
      produces:
        - application/vnd.geo+json
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      responses:
        200:
          description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      responses:
        200:
          description: The root service end-point
      x-monitor: false
      produces:
        - application/json
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      responses:
        200:
          description: Gets information about the service
      x-monitor: true
      produces:
        - application/json
  /_info/name:
    get:
      tags:
        - Service information
        - Service name
      responses:
        200:
          description: Gets the name of the service
      x-monitor: false
      produces:
        - application/json; charset=utf-8
  /_info/version:
    get:
      tags:
        - Service information
        - Service version
      responses:
        200:
          description: Gets the running version of the service
      x-monitor: false
      produces:
        - application/json; charset=utf-8
  /_info/home:
    get:
      tags:
        - Service information
        - Service homepage
      responses:
        200:
          description: Redirects to the home page
      x-monitor: false
