openapi: 3.0.0
info:
  version: 0.0.11
  title: Kartotherian
  description: Renders map tiles
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: MediaWiki maps development
    url: http://mediawiki.org/wiki/Maps
  license:
    name: Apache2 license
    url: http://www.apache.org/licenses/LICENSE-2.0

paths:
  # Tiles handler
  /{src}/{z}/{x}/{y}.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders an image tile for the given source, zoom, and coordinates.
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
            application/x-protobuf:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: Get a tile in the middle of the ocean, with overzoom
          request:
            params:
              src: osm-intl
              z: 11
              x: 828
              y: 655
              format: png
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png

  # Tiles handler with scaling
  /{src}/{z}/{x}/{y}@{scale}x.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders an image tile for the given source, zoom, and coords, with scaling.
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: Get a scaled tile
          request:
            params:
              src: osm-intl
              z: 11
              x: 828
              y: 655
              scale: 1.5
              format: png
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  # Source info
  /{src}/info.json:
    get:
      tags:
        - tileinfo
      responses:
        200:
          description: Gets information about the osm-intl source
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-amples:
        - title: Get service info for osm-intl
          request:
            params:
              src: osm-intl
          response:
            status: 200
            headers:
              content-type: application/json; charset=utf-8
            body:
              tilejson: 2.1.0
              attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
              bounds: [ -180, -85.0511, 180, 85.0511 ]
              center: [ -69.4336, 59.1309, 3 ]
              format: "png8:m=h"
              maxzoom: 19
              minzoom: 0
              name: osm-intl
              scale: "1"
              source: "sourceref:///?ref=babel"
              tiles:
                [ "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png" ]

  # Private source info
  /private-info/info.json:
    get:
      tags:
        - tileinfo
      responses:
        400:
          description: Returns error describing that given tile source is private
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false # keep this x-ample for testing purposes, source doesnt exist in prod
      x-amples:
        - title: private tile service info for osm-intl
          response:
            status: 400
            headers:
              content-type: application/json; charset=utf-8
            body:
              detail: Source info is not public
              internalURI: "http://localhost:6533/private-info/info.json"
              internalMethod: get

  # Maki icon markers (pushpins)
  # /v4/marker/{base}-{size}-{symbol}+{color}.png:
  /v4/marker/pin-m-fuel+ffffff.png:
    get:
      responses:
        200:
          description: Renders pushpin marker of a given color and size with an icon.
          content:
            image/png:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: Get pushpin marker with an icon
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  # /v4/marker/{base}-{size}-{symbol}+{color}@{scale}x.png:
  /v4/marker/pin-m-fuel+ffffff@2x.png:
    get:
      tags:
        - marker
        - maki
      responses:
        200:
          description: Renders 2x scaled pushpin marker of a given color and size with an icon.
          content:
            image/png:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: Get scaled pushpin marker with an icon
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  # /v4/marker/{base}-{size}+{color}.png:
  /v4/marker/pin-m+ffffff.png:
    get:
      responses:
        200:
          description: Renders a pushpin marker of a given color and size without an icon
          content:
            image/png:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: pushpin marker without an icon
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  # /v4/marker/{base}-{size}+{color}@{scale}x.png:
  /v4/marker/pin-m+ffffff@2x.png:
    get:
      responses:
        200:
          description: Renders 2x scaled pushpin marker of a given color and size without an icon.
          content:
            image/png:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: scaled pushpin marker without an icon
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  # Map snapshots
  /img/{src},{z},{lat},{lon},{w}x{h}.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders requested map region as an image (static map snapshot)
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: Small stiched static map
          request:
            params:
              src: osm-intl
              z: 1
              lat: 0
              lon: 0
              w: 100
              h: 100
              format: png
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  /img/{src},{z},{lat},{lon},{w}x{h}@{scale}x.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      responses:
        200:
          description: Renders requested map region as a scaled image (static map snapshot)
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: Small stiched static map scaled
          request:
            params:
              src: osm-intl
              z: 1
              lat: 0
              lon: 0
              w: 100
              h: 100
              format: png
              scale: 2
          response:
            status: 200
            headers:
              content-type: image/png
            body:
              type: png
  # geoline service
  /geoline?getgeojson=1&ids={ids}:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given line from Wikidata item ids
          content:
            application/vnd.geo+json:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: get Moscow geojson
          request:
            params:
              ids: Q649
          response:
            status: 200
            headers:
              content-type: application/vnd.geo+json; charset=utf-8
  # geoshape service
  /geoshape?getgeojson=1&ids={ids}:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given shape from Wikidata item ids
          content:
            application/vnd.geo+json:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: get Lake Garda geojson
          request:
            params:
              ids: Q6414
          response:
            status: 200
            headers:
              content-type: application/vnd.geo+json; charset=utf-8
  # geopoint service
  /geopoint?getgeojson=1&ids={ids}:
    get:
      tags:
        - kartotherian
        - maps
        - geojson
      responses:
        200:
          description: Returns a json representation of a given point from Wikidata item ids
          content:
            application/vnd.geo+json:
              schema:
                type: string
                format: binary
      x-monitor: false
      x-amples:
        - title: get Berliner Fernsehturm geojson
          request:
            params:
              ids: Q151356
          response:
            status: 200
            headers:
              content-type: application/vnd.geo+json; charset=utf-8
            body:
              type: FeatureCollection
              features:
                - type: Feature
                  id: Q151356
                  properties: {}
                  geometry:
                    type: Point
                    coordinates: [ 13.409444444, 52.520833333 ]

  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      responses:
        200:
          description: Gets robots.txt
      x-monitor: false
  /:
    get:
      tags:
        - Root
      responses:
        200:
          description: The root service end-point
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      responses:
        200:
          description: Gets information about the service
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: true
      x-amples:
        - title: get the service info
          response:
            status: 200
            headers:
              content-type: application/json; charset=utf-8
            body:
              name: kartotherian
              version: 2.1.0
              description: Kartotherian - a suite of map tile rendering and map serving software
              home: "https://github.com/kartotherian/kartotherian"

  /_info/name:
    get:
      tags:
        - Service information
        - Service name
      responses:
        200:
          description: Gets the name of the service
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
  /_info/version:
    get:
      tags:
        - Service information
        - Service version
      responses:
        200:
          description: Gets the running version of the service
          content:
            application/json:
              schema:
                type: string
                format: binary
      x-monitor: false
  /_info/home:
    get:
      tags:
        - Service information
        - Service homepage
      responses:
        200:
          description: Redirects to the home page
      x-monitor: false
