pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: production
        build: production
        publish:
          image:
            tags: [kartotherian]

