@startuml
() tiles
() "geolines\ngeoshapes" as geoshapes_req
() "static maps" as staticmaps
[Varnish]
component Kartotherian {
    component geoshapes
    component "snapshot (static maps)" as snapshot {
        component mapdata
    }
}
cloud OSM
cloud WDQS
cloud commons [
    commons.wikimedia.org
]
cloud Tegola
database Postgres [
    Postgres
    --
    OSM
    --
    gis table
]
package mapnik {
    component mapnik_raster_renderer
}

Kartotherian <--> mapnik_raster_renderer : get raster image
mapnik_raster_renderer --> Tegola
geoshapes --> Postgres : get OSM tag for given Wikidata ID
geoshapes --> WDQS : get GeoJSON\nfrom\nWQDS
mapdata --> commons : get GeoJSON\nfrom\nData namespace
mapdata --> geoshapes
tiles -- Varnish
geoshapes_req -- Varnish
staticmaps -- Varnish

OSM -> Postgres: import maps data

Varnish --> Kartotherian
@enduml
