@startuml
() tiles
() "geolines\ngeoshapes" as geoshapes_req
() "static maps" as staticmaps
[Varnish]
component Kartotherian {
    component geoshapes
    component "snapshot (static maps)" as snapshot {
        component mapdata
    }
}
cloud OSM
cloud WDQS
cloud commons [
    commons.wikimedia.org
]
cloud Swift
database Redis
database Postgres [
    Postgres
    --
    OSM
    --
    gis table
]
package mapnik {
    component mapnik_mvt_renderer
    component mapnik_raster_renderer
}

mapnik_mvt_renderer --> Postgres : query OSM data
Kartotherian <--> mapnik_raster_renderer : get raster image

geoshapes --> Postgres : get OSM tag for given Wikidata ID
geoshapes --> WDQS : get GeoJSON\nfrom\nWQDS
mapdata --> commons : get GeoJSON\nfrom\nData namespace
mapdata --> geoshapes
tiles -- Varnish
geoshapes_req -- Varnish
staticmaps -- Varnish

OSM -> Postgres: import maps data

Kartotherian --> Swift: get vector-tiles\nfor rendering
Varnish --> Kartotherian
@enduml
