@startuml
|maps::master cron|
start
repeat
:invoke
replication
script;
|#AntiqueWhite|replication script (imposm)|
:pulls data from OSM using
imposm with hourly strategy;
:imposm stores
data into the DB;
|PostgreSQL DB|
:receives data from
imposm;
|replication script (imposm)|
:script runs custom
SQL function for
indexes and to
populate the admin
table;
:script creates a
list of affected
tiles to pass
to tile generation;
detach
|Tile generation|
:Every 24 hours send tile invalidation events;
:Every 24 hours pregenerate invalidated tiles;
detach
|replication script (imposm)|
|maps::master cron|
repeatwhile (<b>repeat every 12 hours)
:SIGTERM;
end
@enduml
