@startuml
actor User
User -> MediaWiki: action=view
MediaWiki -> Kartographer: wikitext with <mapframe>
Kartographer -> MediaWiki: <img> with revid in URL
MediaWiki -> User: HTML
User -> Kartotherian: image URL with revid
Kartotherian -> Kartographer: geodata API request with revid
Kartographer -> Kartotherian: GeoJSON
Kartotherian -> User : .png
@enduml
